tab = [ [(20, "Rouge")],
        [(35, "Rouge")],
        [(25, "Rouge"), (5, "Bleu")],
        [(35, "Rouge"), (18, "Bleu")],
        [(5, "Rouge"), (27, "Bleu")],
        [(15, "Rouge"), (15, "Bleu"), (5, "Vert")],
        [(20, "Rouge"), (20, "Bleu"), (5, "Vert")],
        [(10, "Rouge"), (20, "Bleu"), (14, "Vert")],
        [(30, "Vert")],
        [(102, "Bleu")],
        [(6, "Rouge"), (12, "Bleu"), (12, "Vert"), (3, "Jaune")],
        [(15, "Bleu"), (10, "Vert"), (5, "Jaune")],
        [(50, "Bleu"), (23, "Vert")],
        [(49, "Rouge"), (15, "Bleu"), (10, "Vert"), (9, "Jaune")],
        [(20, "Rouge"), (15, "Bleu"), (12, "Vert"), (10, "Jaune"), (5, "Rose")],
        [(40, "Vert"), (8, "Jaune")],
        [(12, "Jaune")],
        [(80, "Vert")],
        [(10, "Vert"), (4, "Jaune"), (5, "Jaune"), (15, "Rose")],
        [(6, "Noir")],
        [(40, "Jaune"), (14, "Rose")],
        [(16, "Blanc")],
        [(7, "Noir"), (7, "Blanc")],
        [(20, "Bleu"), (1, "Vert")],
        [(25, "Yellow"), (10, "Violet")],
        [(23, "Rose"), (4, "Zebra")],
        [(100, "Rouge"), (60, "Bleu"), (45, "Vert"), (45, "Jaune")],
        [(6, "Plomb")],
        [(50, "Jaune"), (15, "Jaune")],
        [(9, "Plomb")],
        [(8, "Noir"), (8, "Blanc"), (8, "Zebra"), (2, "Zebra")],
        [(15, "Noir"), (20, "Blanc"), (10, "Violet")],
        [(20, "Rouge"), (13, "Jaune")],
        [(160, "Jaune"), (6, "Zebra")],
        [(35, "Rose"), (30, "Noir"), (25, "Blanc"), (5, "Arc-en-ciel")],
        [(140, "Rose"), (20, " Vert")],
        [(25, "Noir"), (25, "Blanc"), (7, " Blanc"), (10, "Zebra"), (15, "Plomb")],
        [(42, "Rose"), (17, "Blanc"), (10, "Zebra"), (14, "Plomb"), (2, "Ceramique")],
        [(10, "Noir"), (10, "Blanc"), (20, "Zebra"), (18, "Arc-en-ciel"), (2, "Arc-en-ciel")],
        [(1, "Moab")],
        [(60, "Noir"), (7, "Blanc")],
        [(10, "Arc-en-ciel"), (5, "Arc-en-ciel")],
        [(10, "Arc-en-ciel"), (7, "Ceramique")],
        [(40, "Zebra")],
        [(180, "Rose"), (10, "Violet"), (4, "Plomb"), (25, "Arc-en-ciel")],
        [(6, "Ceramique")],
        [(70, "Rose"), (12, "Ceramique")],
        [(40, "Rose"), (30, "Violet"), (40, "Arc-en-ciel"), (3, "Ceramique")],
        [(343, "Vert"), (20, "Zebra"), (20, "Arc-en-ciel"), (10, "Arc-en-ciel"), (18, "Ceramique")],
        [(20, "Rouge"), (8, " Plomb"), (20, "Ceramique"), (2, "Moab")],
        [(10, "Arc-en-ciel"), (15, "Ceramique")],
        [(25, "Arc-en-ciel"), (10, "Ceramique"), (2, "Moab")],
        [(80, "Rose"), (3, "Moab")],
        [(35, "Ceramique"), (2, "Moab")],
        [(45, "Ceramique"), (1, "Moab")],
        [(40, "Arc-en-ciel"), (1, "Moab")],
        [(40, "Arc-en-ciel"), (4, "Moab")],
        [(15, "Ceramique"), (10, "Ceramique"), (5, "Moab")],
        [(50, "Plomb"), (20, "Ceramique"), (10, "Ceramique")],
        [(1, "Bfb")],
        [(150, "Zebra"), (5, "Moab")],
        [(250, "Violet"), (15, "Arc-en-ciel"), (5, "Moab"), (2, "Moab")],
        [(75, "Plomb"), (122, "Ceramique")],
        [(6, "Moab"), (3, " Moab")],
        [(100, "Zebra"), (70, "Arc-en-ciel"), (50, "Ceramique"), (3, "Moab"), (2, "Bfb")],
        [(8, "Moab"), (3, "Moab")],
        [(13, "Ceramique"), (8, "Moab")],
        [(4, "Moab"), (1, "Bfb")],
        [(40, "Noir"), (40, "Plomb"), (50, "Ceramique")],
        [(120, "Blanc"), (200, "Arc-en-ciel"), (4, "Moab")],
        [(30, "Ceramique"), (10, "Moab")],
        [(30, "Ceramique"), (2, "Bfb")],
        [(8, "Moab"), (2, "Bfb")],
        [(50, "Ceramique"), (60, "Ceramique"), (25, "Ceramique"), (1, "Bfb")],
        [(14, "Plomb"), (12, "Plomb"), (3, "Moab"), (7, "Bfb")],
        [(60, "Ceramique")],
        [(11, "Moab"), (5, "Bfb")],
        [(80, "Violet"), (150, "Arc-en-ciel"), (75, "Ceramique"), (72, "Ceramique"), (1, "Bfb")],
        [(500, "Arc-en-ciel"), (4, "Bfb"), (2, "Bfb")],
        [(1, "Zomg")],
        [(17, "Bfb")],
        [(10, "Bfb"), (5, "Bfb")],
        [(40, "Ceramique"), (40, "Ceramique"), (40, "Ceramique"), (30, "Moab")],
        [(50, "Moab"), (10, "Bfb")],
        [(2, "Zomg")],
        [(5, "Bfb")],
        [(4, "Zomg")],
        [(18, "Moab"), (8, "Bfb"), (2, "Zomg")],
        [(20, "Moab"), (8, "Bfb")],
        [(50, "Plomb"), (3, "Ddt")],
        [(100, "Ceramique"), (20, "Bfb")],
        [(50, "Moab"), (4, "Zomg")],
        [(10, "Bfb"), (6, "Ddt")],
        [(25, "Bfb"), (6, "Zomg")],
        [(500, "Violet"), (250, "Plomb"), (50, "Moab"), (30, "Ddt")],
        [(40, "Moab"), (30, "Bfb"), (6, "Zomg")],
        [(2, "Zomg")],
        [(30, "Bfb"), (8, "Zomg")],
        [(60, "Moab"), (9, "Ddt")],
        [(1, "Bad")],
        ]

def round_desire(round_actuel: int) -> list:
    liste_round = [ballon[1] for ballon in tab[round_actuel - 1] for _ in range(ballon[0])]
    return liste_round